DEFAULT_NUM_LIGHT_POSITIONS = 16
DEFAULT_NUM_OBJECTS = 128
DEFAULT_NUM_ROADMAPS = 30_000

NUM_TS_PAST = 10
NUM_TS_FUTURE = 80
NUM_TS_ALL = 1 + NUM_TS_PAST + NUM_TS_FUTURE

DIST_INTERPOLATION = 1.01

NUM_PATHS = 10
NUM_POINTS_PER_PATH = 300
